//! Filterable fields per category.

/// Filterable fields for a category (excludes common metadata).
/// Returns `None` for unknown categories.
pub fn filterable_fields(category: &str) -> Option<&'static [&'static str]> {
    Some(match category {
        "spell" => &[
            "actions",
            "bloodline",
            "component",
            "deity",
            "element",
            "heighten_group",
            "level",
            "patron_theme",
            "rarity",
            "saving_throw",
            "school",
            "spell_type",
            "tradition",
            "trait",
        ],
        "feat" => &["feat", "level", "rarity", "trait"],
        "deity" => &[
            "alignment",
            "area_of_concern",
            "attribute",
            "cleric_spell",
            "deity",
            "divine_font",
            "domain",
            "domain_alternate",
            "domain_primary",
            "favored_weapon",
            "follower_alignment",
            "pantheon",
            "sanctification",
            "skill",
            "spell",
            "trait",
        ],
        "ancestry" => &[
            "attribute",
            "attribute_flaw",
            "hp",
            "language",
            "rarity",
            "size",
            "trait",
        ],
        "class" => &[
            "attack_proficiency",
            "attribute",
            "defense_proficiency",
            "hp",
            "rarity",
            "skill_proficiency",
        ],
        "creature" => &[
            "alignment",
            "creature_ability",
            "hp",
            "immunity",
            "language",
            "level",
            "rarity",
            "size",
            "skill",
            "strongest_save",
            "trait",
            "weakest_save",
        ],
        "equipment" => &["actions", "level", "rarity", "trait"],
        "background" => &["attribute", "feat", "rarity", "skill"],
        "heritage" => &["rarity"],
        "archetype" => &["archetype", "archetype_category", "level", "rarity"],
        "action" => &["actions", "rarity"],
        "hazard" => &["level", "rarity", "trait"],
        "condition" => &["rarity"],
        "ritual" => &["level", "rarity", "school", "trait"],
        "domain" => &["deity", "domain", "spell"],
        "weapon" => &["damage_type", "deity", "level", "rarity", "trait"],
        "armor" => &["level", "rarity"],
        "shield" => &["hp", "level", "rarity"],
        "vehicle" => &["hp", "level", "rarity", "size", "trait"],
        "disease" => &["level", "rarity", "saving_throw", "trait"],
        "curse" => &["level", "rarity", "school", "trait"],
        "bloodline" => &["bloodline", "rarity", "skill", "spell", "tradition"],
        "mystery" => &["domain", "rarity", "skill", "spell"],
        "eidolon" => &[
            "alignment",
            "language",
            "rarity",
            "size",
            "skill",
            "tradition",
            "trait",
        ],
        "patron" => &["rarity", "skill", "spell", "tradition"],
        "relic" => &["aspect", "element", "rarity", "school", "trait"],
        "familiar-ability" => &["rarity"],
        "familiar-specific" => &["familiar_ability", "rarity", "trait"],
        "animal-companion" => &["hp", "level", "rarity", "size", "skill", "trait"],
        "plane" => &["alignment", "rarity", "trait"],
        "language" => &["rarity"],
        "trait" => &["rarity", "trait", "trait_group"],
        "class-feature" => &["level", "rarity"],
        "draconic-exemplar" => &["rarity", "skill", "spell", "tradition"],
        _ => return None,
    })
}
