//! Known AON categories with filterable fields and grouping.

mod fields;
mod suggest;

pub use fields::filterable_fields;
pub use suggest::{suggest_category, suggest_from};

/// All known AON category keys.
pub const ALL_CATEGORIES: &[&str] = &[
    "action",
    "ammunition",
    "ancestry",
    "anchor",
    "animal-companion",
    "animal-companion-advanced",
    "animal-companion-specialization",
    "animal-companion-unique",
    "apparition",
    "arcane-school",
    "arcane-thesis",
    "archetype",
    "armor",
    "armor-group",
    "article",
    "background",
    "bloodline",
    "campsite-meal",
    "category-page",
    "cause",
    "class",
    "class-feature",
    "class-kit",
    "class-sample",
    "computer",
    "condition",
    "connection",
    "conscious-mind",
    "creature",
    "creature-ability",
    "creature-adjustment",
    "creature-family",
    "creature-theme-template",
    "cult-activity",
    "curse",
    "deity",
    "deity-category",
    "deviant-ability-classification",
    "disease",
    "doctrine",
    "domain",
    "draconic-exemplar",
    "druidic-order",
    "eidolon",
    "element",
    "epithet",
    "equipment",
    "faction",
    "familiar-ability",
    "familiar-specific",
    "fatal-method",
    "feat",
    "fighting-style",
    "follower",
    "grim-fascination",
    "hazard",
    "hazard-family",
    "hellknight-order",
    "heritage",
    "hunters-edge",
    "hybrid-study",
    "ikon",
    "implement",
    "innovation",
    "instinct",
    "item-bonus",
    "kingdom-event",
    "kingdom-structure",
    "language",
    "leadership-style",
    "lesson",
    "methodology",
    "muse",
    "mystery",
    "mythic-calling",
    "paradox",
    "patron",
    "plane",
    "planet",
    "practice",
    "racket",
    "relic",
    "research-field",
    "ritual",
    "rules",
    "runesmith-rune",
    "set-relic",
    "shield",
    "sidebar",
    "siege-weapon",
    "skill",
    "skill-general-action",
    "solar-manifestation",
    "source",
    "specialization",
    "spell",
    "starship-scene",
    "style",
    "subconscious-mind",
    "tactic",
    "tenet",
    "tradition",
    "trait",
    "vehicle",
    "warfare-army",
    "warfare-tactic",
    "way",
    "weapon",
    "weapon-group",
    "weather-hazard",
];

/// Group structure for hierarchical display.
pub struct CategoryGroup {
    pub name: &'static str,
    pub members: &'static [&'static str],
}

/// Categories organized into display groups.
pub const CATEGORY_GROUPS: &[CategoryGroup] = &[
    CategoryGroup {
        name: "Character Building",
        members: &[
            "ancestry",
            "heritage",
            "background",
            "class",
            "class-feature",
            "class-kit",
            "class-sample",
            "feat",
        ],
    },
    CategoryGroup {
        name: "Class Options",
        members: &[
            "apparition",
            "arcane-school",
            "arcane-thesis",
            "bloodline",
            "cause",
            "conscious-mind",
            "doctrine",
            "draconic-exemplar",
            "druidic-order",
            "eidolon",
            "element",
            "epithet",
            "hunters-edge",
            "hybrid-study",
            "ikon",
            "implement",
            "innovation",
            "instinct",
            "lesson",
            "methodology",
            "muse",
            "mystery",
            "patron",
            "practice",
            "racket",
            "research-field",
            "style",
            "subconscious-mind",
            "tactic",
            "way",
            "fatal-method",
            "grim-fascination",
            "runesmith-rune",
            "connection",
            "fighting-style",
            "leadership-style",
            "paradox",
            "solar-manifestation",
            "specialization",
        ],
    },
    CategoryGroup {
        name: "Magic",
        members: &["spell", "ritual", "domain", "tradition"],
    },
    CategoryGroup {
        name: "Equipment",
        members: &[
            "equipment",
            "armor",
            "armor-group",
            "shield",
            "weapon",
            "weapon-group",
            "item-bonus",
            "siege-weapon",
            "ammunition",
            "computer",
        ],
    },
    CategoryGroup {
        name: "Creatures & Companions",
        members: &[
            "creature",
            "creature-ability",
            "creature-adjustment",
            "creature-family",
            "creature-theme-template",
            "animal-companion",
            "animal-companion-advanced",
            "animal-companion-specialization",
            "animal-companion-unique",
            "familiar-ability",
            "familiar-specific",
            "follower",
        ],
    },
    CategoryGroup {
        name: "World & Lore",
        members: &[
            "deity",
            "deity-category",
            "action",
            "archetype",
            "condition",
            "disease",
            "curse",
            "hazard",
            "language",
            "plane",
            "relic",
            "set-relic",
            "skill",
            "skill-general-action",
            "trait",
            "vehicle",
            "faction",
            "planet",
            "hazard-family",
        ],
    },
    CategoryGroup {
        name: "Rules & Reference",
        members: &[
            "rules",
            "article",
            "anchor",
            "starship-scene",
            "campsite-meal",
            "category-page",
            "cult-activity",
            "deviant-ability-classification",
            "hellknight-order",
            "kingdom-event",
            "kingdom-structure",
            "mythic-calling",
            "sidebar",
            "source",
            "tenet",
            "warfare-army",
            "warfare-tactic",
            "weather-hazard",
        ],
    },
];

/// Emoji icon for a category.
pub fn category_icon(cat: &str) -> &'static str {
    match cat {
        "spell" | "ritual" => "✨",
        "feat" => "⭐",
        "deity" => "🔱",
        "ancestry" => "🧬",
        "heritage" => "🌿",
        "class" => "⚔️",
        "creature" => "🐉",
        "equipment" | "armor" | "weapon" | "shield" => "🛡️",
        "background" => "📜",
        "archetype" => "🏛️",
        "action" => "⚡",
        "condition" | "disease" | "curse" => "💀",
        "hazard" => "⚠️",
        "trait" => "🏷️",
        "domain" => "🌐",
        _ => "📄",
    }
}
