name: CI

on:
  push:
    branches: [main]
    paths-ignore: ["**.md", "LICENSE*", ".gitignore"]
  pull_request:
    paths-ignore: ["**.md", "LICENSE*", ".gitignore"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    # Default os matrix is 3-OS (incl. windows).
    uses: jhheider/rust-ci/.github/workflows/ci.yml@v1
    with:
      coverage: true
    secrets: inherit
